container:
  image: ubuntu:bionic

make_task:
  update_script: apt-get update
  etckeeper_script: apt-get install -y etckeeper
  upgrade_script: apt-get dist-upgrade -y
  depends_script: apt-get install -y build-essential git
  lsb_script: sort /etc/os-release
  packages_script: dpkg -l
  make_script: make

